def forca(erros):
    if (erros == 0):
        print()
        print("|----- ")
        print("|    | ")
        print("|      ")
        print("|      ")
        print("|      ")
        print("|      ")
        print("_      ")
        print()
     #Não botei todos!! e está indentado!
    elif(erros == 1):
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|        ")
        print("|      ")
        print("|        ")
        print("_      ")
        print()
    elif(erros == 2):
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    |   ")
        print("|    | ")
        print("|        ")
        print("_      ")
        print()
    elif(erros == 3):
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    |\\ ")
        print("|    | ")
        print("|        ")
        print("_      ")
        print()
    elif(erros == 4):
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif(erros == 5):
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ")
        print("|    | ")
        print("|     \\ ")
        print("_      ")
        print()
    elif(erros == 6):
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ")
        print("|    | ")
        print("|   / \\ ")
        print("_      ")
        print()

def perdeu(palavra_secreta):
    print("Puxa, você foi enforcado!")
    print("A palavra era {}".format(palavra_secreta))
    print("    _______________         ")
    print("   /               \\       ")
    print("  /                 \\      ")
    print("//                   \\/\\  ")
    print("\\|   XXXX     XXXX   | /   ")
    print(" |   XXXX     XXXX   |/     ")
    print(" |   XXX       XXX   |      ")
    print(" |                   |      ")
    print(" \\__      XXX      __/     ")
    print("   |\\     XXX     /|       ")
    print("   | |           | |        ")
    print("   | I I I I I I I |        ")
    print("   |  I I I I I I  |        ")
    print("   \\_             _/       ")
    print("     \\_         _/         ")
    print("       \\_______/           ")


def venceu():
    print("Parabéns, você ganhou!")
    print("       ___________      ")
    print("      '._==_==_=_.'     ")
    print("      .-\\:      /-.    ")
    print("     | (|:.     |) |    ")
    print("      '-|:.     |-'     ")
    print("        \\::.    /      ")
    print("         '::. .'        ")
    print("           ) (          ")
    print("         _.' '._        ")
    print("        '-------'       ")
